---
output: rmarkdown::github_document
editor_options: 
  chunk_output_type: console
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r include=FALSE}
knitr::opts_chunk$set(warning=FALSE, comment="")
library(tidyverse)
library(magrittr)
```

## Data
```{r}
fn <- "snapshot.csv"
snapshot <- readr::read_csv(fn, col_types=c("ccdcc"))
snapshot$balance <- as.integer(snapshot$balance)
summary(snapshot)
```

## Seed
```{r}
block <- 18232769 # https://etherscan.io/block/18232769
block_hash <- "0xdeb8571027ec886665a182f25795fb612fb78d2c0fdd26b8ef160f1b54ff593a"
# Convert block hash to ASCII
# Take the sum over integer vector to set seed
seed <- sum(utf8ToInt(block_hash))
cat("Seed:", seed, "\n")
```

## Code
```{r}
subtract_multi <- function(x, y) {
  for (i in y) {
    where <- match(i, x)
    if (!is.na(where)) {
      x <- x[-where]
    }
  }
  return(x)
}

pick <- function(df,
                 contracts=c(),
                 address_remove=NULL,
                 address_subtract=NULL,
                 address_max=Inf,
                 address_pick=NA,
                 address_replace=FALSE) {

  df <- df %>%
    dplyr::filter(name %in% contracts) %>%
    dplyr::filter(!(address %in% address_remove))
  
  df_by_address <- df %>%
    dplyr::group_by(address) %>%
    dplyr::summarise(
      balance = ifelse(sum(balance) <= address_max, sum(balance), address_max)
    )
  
  pool <- df_by_address %>%
    dplyr::arrange(address) %>%
    dplyr::select(address, balance) %>%
    purrr::pmap(function(address, balance) {
      base::rep(address, balance)
    }) %>%
    unlist() %>%
    subtract_multi(address_subtract)
  
  if (is.na(address_pick)) {
    return(pool)
  } else {
    return(base::sample(pool, size=address_pick, replace=address_replace))
  }
}

tally <- function(x) {
  if (length(x) > 0) {
    unlist(x) %>%
    data.frame(address = .) %>%
    dplyr::group_by(address) %>%
    dplyr::summarise(
      amount = n()
    ) %>%
    dplyr::arrange(desc(amount), address)
  }
}
```

```{r}
base::set.seed(seed)

address_remove <- c(
  "0x3a3548e060be10c2614d0a4cb0c03cc9093fd799",
  "0x4b76837f8d8ad0a28590d06e53dcd44b6b7d4554",
  "0x0887773b5f43c58f0da7bd0402fc2d49482eb845",
  "0xcda72070e455bb31c7690a170224ce43623d0b6f",
  "0x41a322b28d0ff354040e2cbc676f0320d8c8850d",
  "0x000000000000000000000000000000000000dead",
  "0xc6400A5584db71e41B0E5dFbdC769b54B91256CD",
  "0xfd22004806a6846ea67ad883356be810f0428793",
  "0x0E5c3E22b7239CEf46f56741ff66369f3CfECb77",
  "0xc3c9737cce778d7583f31ae7c4f2ab8782ed51e5",
  "0xA62DA2Ea9F5bB03a58174060535ae32131973178",
  "0xE16dF6503Acd3c79b6E032f62c61752bEC16eeF2",
  "0x9769334FC882775F4951865aA473481880669D47",
  "0x3852471D266d9e2222CA9Fdd922BAFC904Dc49e5",
  "0x88D3574660711e03196aF8A96f268697590000Fa",
  "0x885846850aaBf20d8f8e051f400354D94a32FF55",
  "0x61D9d9cc8C3203daB7100eA79ceD77587201C990",
  "0x7bA3e8f17582462676c44dd143388eD4B6b20655",
  "0xfe3b3F0D64F354b69A5B40D02f714E69cA4B09bd",
  "0x8889EBB11295F456541901f50BCB5f382047cAaC",
  "0x4269AaDfd043b58cbA893BfE6029C9895C25cb61",
  "0xbDf82b13580b918ebc3c24b4034E8468EA168E21",
  "0x83EE335ca72759CAeDeD7b1afD11dCF75F48436b",
  "0xddA3cb2741FaC4a87CAebec9EFC7963087304097",
  "0xF9e129817BC576f937e4774E3C3Aec98787Cfb91",
  "0x8e63380aC1e34c7D61bf404aF63e885875C18Ce3",
  "0xaf5c021754Ab82Bf556BC6C90650dE21Cf92d1c7",
  "0x7f3774EAdae4beB01919deC7f32A72e417Ab5DE3",
  "0xC03E57b6acE9Dd62C84A095E11E494E3C8FD4D42",
  "0xe70d73c76fF3b4388EE9C58747F0EaA06C6b645B",
  "0x8BA68CFe71550EfC8988D81d040473709B7F9218",
  "0xa743c8c57c425B84Cb2eD18C6B9ae3aD21629Cb5",
  "0x1b7844CfaE4C823Ac6389855D47106a70c84F067",
  "0x76D078D7e5755B66fF50166863329D27F2566b43"
)

hodlers_remove <- c(
  ""
)

allow_artist_phase1      <- pick(snapshot, contracts=c("SuperRare","SuperRare2","SuperRare3","KillerAcid3"),address_remove=address_remove,address_max=1)
allow_gradient           <- pick(snapshot, contracts=c("gradient"),address_remove=tolower(address_remove), address_max=1)
allow_raw                <- pick(snapshot, contracts=c("raw"), address_remove=tolower(address_remove),address_max=1)
allow_singles            <- pick(snapshot, contracts=c("65291/1s"), address_remove=tolower(address_remove),address_max=1)
allow_intern             <- pick(snapshot, contracts=c("intern"),address_remove=tolower(address_remove), address_max=1)



allow_artist_phase2    <- pick(snapshot, contracts=c("Microdoses","KillerAcid","KillerAcid2","KillerAcid4","KillerAcid5","KillerAcid6","KillerAcid7","KillerAcid8","KillerAcidfun","KillerAcidfunEditions","TropicalStorm","Noble","ManMachine"), address_remove=tolower(address_remove),address_subtract=allow_artist_phase1,address_max=1)



```




## Allow Artist Phase 1
```{r}
c(allow_artist_phase1) %>%
tally() %T>%
readr::write_csv(file="allow_artist_phase1.csv", col_names=FALSE) %>%
print(n=Inf)
```

## Allow Gradient
```{r}
c(allow_gradient) %>%
tally() %T>%
readr::write_csv(file="allow_gradient.csv", col_names=FALSE) %>%
print(n=Inf)
```

## Allow Intern
```{r}
c(allow_intern) %>%
tally() %T>%
readr::write_csv(file="allow_intern.csv", col_names=FALSE) %>%
print(n=Inf)
```

## Allow 6529
```{r}
c(allow_raw, allow_singles) %>%
tally() %T>%
readr::write_csv(file="allow_6529.csv", col_names=FALSE) %>%
print(n=Inf)
```



## Allow Artist Phase 3
```{r}
c(allow_artist_phase2) %>%
tally() %T>%
readr::write_csv(file="allow_artist_phase3.csv", col_names=FALSE) %>%
print(n=Inf)
```




## Versioning
```{r}
R.version$version.string
packageVersion("tidyverse")
packageVersion("magrittr")
```
