---
output: rmarkdown::github_document
editor_options: 
  chunk_output_type: console
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r include=FALSE}
knitr::opts_chunk$set(warning=FALSE, comment="")
library(tidyverse)
library(magrittr)
```

## Data
```{r}
fn <- "16725069.csv"
snapshot <- readr::read_csv(fn, col_types=c("ccdcc"))
snapshot$balance <- as.integer(snapshot$balance)
summary(snapshot)
```

## Seed
```{r}
block <- 16725969 # https://etherscan.io/block/16725969
block_hash <- "0x6f854a82cac7bf86ea59e09a03ef8181b4e56ee66de5435bd4d46ade29d9f64d"
# Convert block hash to ASCII
# Take the sum over integer vector to set seed
seed <- sum(utf8ToInt(block_hash))
cat("Seed:", seed, "\n")
```

## Code
```{r}
subtract_multi <- function(x, y) {
  for (i in y) {
    where <- match(i, x)
    if (!is.na(where)) {
      x <- x[-where]
    }
  }
  return(x)
}

pick <- function(df,
                 contracts=c(),
                 address_remove=NULL,
                 address_subtract=NULL,
                 address_max=Inf,
                 address_pick=NA,
                 address_replace=FALSE) {

  df <- df %>%
    dplyr::filter(name %in% contracts) %>%
    dplyr::filter(!(address %in% address_remove))
  
  df_by_address <- df %>%
    dplyr::group_by(address) %>%
    dplyr::summarise(
      balance = ifelse(sum(balance) <= address_max, sum(balance), address_max)
    )
  
  pool <- df_by_address %>%
    dplyr::arrange(address) %>%
    dplyr::select(address, balance) %>%
    purrr::pmap(function(address, balance) {
      base::rep(address, balance)
    }) %>%
    unlist() %>%
    subtract_multi(address_subtract)
  
  if (is.na(address_pick)) {
    return(pool)
  } else {
    return(base::sample(pool, size=address_pick, replace=address_replace))
  }
}

tally <- function(x) {
  if (length(x) > 0) {
    unlist(x) %>%
    data.frame(address = .) %>%
    dplyr::group_by(address) %>%
    dplyr::summarise(
      amount = n()
    ) %>%
    dplyr::arrange(desc(amount), address)
  }
}
```

```{r}
base::set.seed(seed)

address_remove <- c(
  "0x3a3548e060be10c2614d0a4cb0c03cc9093fd799",
  "0x4b76837f8d8ad0a28590d06e53dcd44b6b7d4554",
  "0x0887773b5f43c58f0da7bd0402fc2d49482eb845",
  "0xcda72070e455bb31c7690a170224ce43623d0b6f",
  "0x41a322b28d0ff354040e2cbc676f0320d8c8850d",
  "0x000000000000000000000000000000000000dead"
)

hodlers_remove <- c(
  ""
)

airdrop_memes     <- pick(snapshot, contracts=c("memes500"),address_remove=address_remove, address_pick=33,address_max=1)
airdrop_neil      <- pick(snapshot, contracts=c("SuperRare","SuperRare2","Foundation"), address_remove=address_remove,address_max=1)

allow_gradient_phase1   <- pick(snapshot, contracts=c("gradient"),address_pick=20, address_max=1)
allow_neil              <- pick(snapshot, contracts=c("Seascapes","VisionsICM","TheUnknown","MysticalWoodland","LightArtAnnual","DANCING"), address_remove=address_remove, address_subtract=airdrop_neil,address_max=1)
allow_memes_1_phase1       <- pick(snapshot, contracts=c("memes500"), address_remove=address_remove, address_subtract=airdrop_memes,address_max=1)
allow_memes_2_phase1       <- pick(snapshot, contracts=c("Memes501_1000"), address_remove=address_remove, address_subtract = c(airdrop_memes, allow_memes_1_phase1),address_pick=300,address_max=1)
allow_memes_3_phase1       <- pick(snapshot, contracts=c("Memes1001_2000"), address_remove=address_remove, address_subtract = c(airdrop_memes, allow_memes_1_phase1, allow_memes_2_phase1),address_pick=300,address_max=1)


allow_gradient_phase2   <- pick(snapshot, contracts=c("gradient"),address_subtract=allow_gradient_phase1, address_max=1)
allow_raw               <- pick(snapshot, contracts=c("raw"), address_remove=address_remove,address_max=1)
allow_singles           <- pick(snapshot, contracts=c("65291/1s"), address_remove=address_remove,address_max=1)
allow_memes_phase2       <- pick(snapshot, contracts=c("memes500","Memes501_1000"), address_remove=address_remove, address_subtract = c(airdrop_memes, allow_memes_1_phase1, allow_memes_2_phase1, allow_memes_3_phase1),address_max=1)

```


## Airdrop Memes
```{r}
c(airdrop_memes) %>%
tally() %T>%
readr::write_csv(file="airdrop_memes.csv", col_names=FALSE) %>%
print(n=Inf)
```

## Airdrop Artist
```{r}
c(airdrop_neil) %>%
tally() %T>%
readr::write_csv(file="airdrop_artist.csv", col_names=FALSE) %>%
print(n=Inf)
```





## Allow Gradient Phase 1
```{r}
c(allow_gradient_phase1) %>%
tally() %T>%
readr::write_csv(file="allow_gradient_phase1.csv", col_names=FALSE) %>%
print(n=Inf)
```

## Allow Artist
```{r}
c(allow_neil) %>%
tally() %T>%
readr::write_csv(file="allow_artist.csv", col_names=FALSE) %>%
print(n=Inf)
```

## Allow Memes 1 Phase 1
```{r}
c(allow_memes_1_phase1) %>%
tally() %T>%
readr::write_csv(file="allow_memes_467_1.csv", col_names=FALSE) %>%
print(n=Inf)
```

## Allow Memes 2 Phase 1
```{r}
c(allow_memes_2_phase1) %>%
tally() %T>%
readr::write_csv(file="allow_memes300_2.csv", col_names=FALSE) %>%
print(n=Inf)
```

## Allow Memes 3 Phase 1
```{r}
c(allow_memes_3_phase1) %>%
tally() %T>%
readr::write_csv(file="allow_memes300_3.csv", col_names=FALSE) %>%
print(n=Inf)
```






## Allow Gradient Phase 2
```{r}
c(allow_gradient_phase2) %>%
tally() %T>%
readr::write_csv(file="allow_gradient_phase2.csv", col_names=FALSE) %>%
print(n=Inf)
```

## Allow 6529
```{r}
c(allow_raw, allow_singles) %>%
tally() %T>%
readr::write_csv(file="allow_6529_phase2.csv", col_names=FALSE) %>%
print(n=Inf)
```

## Allow Memes Phase 2
```{r}
c(allow_memes_phase2) %>%
tally() %T>%
readr::write_csv(file="allow_memes_phase2.csv", col_names=FALSE) %>%
print(n=Inf)
```



## Versioning
```{r}
R.version$version.string
packageVersion("tidyverse")
packageVersion("magrittr")
```
