---
output: rmarkdown::github_document
editor_options: 
  chunk_output_type: console
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r include=FALSE}
knitr::opts_chunk$set(warning=FALSE, comment="")
library(tidyverse)
library(magrittr)
```

## Data
```{r}
fn <- "snapshot.csv"
snapshot <- readr::read_csv(fn, col_types=c("ccdcc"))
snapshot$balance <- as.integer(snapshot$balance)
summary(snapshot)
```

## Seed
```{r}
block <- 16775269 # https://etherscan.io/block/16775269
block_hash <- "0xd713cd8872b387e9b98c57376741b73cfd39ad05c28ba0e0acfb01e572c62bf3"
# Convert block hash to ASCII
# Take the sum over integer vector to set seed
seed <- sum(utf8ToInt(block_hash))
cat("Seed:", seed, "\n")
```

## Code
```{r}
subtract_multi <- function(x, y) {
  for (i in y) {
    where <- match(i, x)
    if (!is.na(where)) {
      x <- x[-where]
    }
  }
  return(x)
}

pick <- function(df,
                 contracts=c(),
                 address_remove=NULL,
                 address_subtract=NULL,
                 address_max=Inf,
                 address_pick=NA,
                 address_replace=FALSE) {

  df <- df %>%
    dplyr::filter(name %in% contracts) %>%
    dplyr::filter(!(address %in% address_remove))
  
  df_by_address <- df %>%
    dplyr::group_by(address) %>%
    dplyr::summarise(
      balance = ifelse(sum(balance) <= address_max, sum(balance), address_max)
    )
  
  pool <- df_by_address %>%
    dplyr::arrange(address) %>%
    dplyr::select(address, balance) %>%
    purrr::pmap(function(address, balance) {
      base::rep(address, balance)
    }) %>%
    unlist() %>%
    subtract_multi(address_subtract)
  
  if (is.na(address_pick)) {
    return(pool)
  } else {
    return(base::sample(pool, size=address_pick, replace=address_replace))
  }
}

tally <- function(x) {
  if (length(x) > 0) {
    unlist(x) %>%
    data.frame(address = .) %>%
    dplyr::group_by(address) %>%
    dplyr::summarise(
      amount = n()
    ) %>%
    dplyr::arrange(desc(amount), address)
  }
}
```

```{r}
base::set.seed(seed)

address_remove <- c(
  "0x3a3548e060be10c2614d0a4cb0c03cc9093fd799",
  "0xc6400a5584db71e41b0e5dfbdc769b54b91256cd",
  "0x4b76837f8d8ad0a28590d06e53dcd44b6b7d4554",
  "0x0887773b5f43c58f0da7bd0402fc2d49482eb845",
  "0xcda72070e455bb31c7690a170224ce43623d0b6f",
  "0x41a322b28d0ff354040e2cbc676f0320d8c8850d",
  "0x000000000000000000000000000000000000dead"
)

hodlers_remove <- c(
  ""
)

airdrop_memes_all   <- pick(snapshot, contracts=c("memes_full_bothSZNs"),address_remove=address_remove, address_pick=15,address_max=1)
airdrop_memes_szn2  <- pick(snapshot, contracts=c("memes_full_SZN2"),address_remove=address_remove,address_subtract=airdrop_memes_all,address_pick=10,address_max=1)
airdrop_gradient    <- pick(snapshot, contracts=c("gradient"),address_pick=5, address_max=1)
airdrop_eric        <- pick(snapshot, contracts=c("SuperRare","OceanIntersection"), address_remove=address_remove,address_pick=30,address_max=1)
airdrop_eric2       <- pick(snapshot, contracts=c("SuperRare","OceanIntersection"), address_remove=address_remove,address_subtract=airdrop_eric,address_max=1)


allow_eric_editions     <- pick(snapshot, contracts=c("BeachBoulevard","EricRubensEditions","WorldofColorEditions","StrangersGiveaway"), address_remove=address_remove, address_subtract=c(airdrop_eric, airdrop_eric2),address_max=1)
allow_gradient_phase1   <- pick(snapshot, contracts=c("gradient"), address_subtract=airdrop_gradient,address_max=1)
allow_memes_1_phase1    <- pick(snapshot, contracts=c("memes_full_bothSZNs"), address_remove=address_remove, address_subtract = c(airdrop_memes_all, airdrop_memes_szn2),address_max=1)
allow_memes_2_phase1    <- pick(snapshot, contracts=c("memes_full_SZN2"), address_remove=address_remove, address_subtract = c(airdrop_memes_all, airdrop_memes_szn2,allow_memes_1_phase1),address_pick=102,address_max=1)
allow_memes_3_phase1    <- pick(snapshot, contracts=c("memes_top_200"), address_remove=address_remove, address_subtract = c(airdrop_memes_all, airdrop_memes_szn2,allow_memes_1_phase1,allow_memes_2_phase1),address_max=1)
allow_memes_4_phase1    <- pick(snapshot, contracts=c("memes_random_69"), address_remove=address_remove, address_subtract = c(airdrop_memes_all, airdrop_memes_szn2,allow_memes_1_phase1,allow_memes_2_phase1,allow_memes_3_phase1),address_pick=69,address_max=1)

allow_raw           <- pick(snapshot, contracts=c("raw"), address_remove=address_remove,address_max=1)
allow_singles       <- pick(snapshot, contracts=c("65291/1s"), address_remove=address_remove,address_max=1)
allow_memes_phase2  <- pick(snapshot, contracts=c("memes_top_500","memes_full_SZN2"), address_remove=address_remove, address_subtract = c(airdrop_memes_all, airdrop_memes_szn2,allow_memes_1_phase1,allow_memes_2_phase1,allow_memes_3_phase1,allow_memes_4_phase1),address_max=1)

```


## Airdrop Memes Both SZNs
```{r}
c(airdrop_memes_all) %>%
tally() %T>%
readr::write_csv(file="airdrop_memes_15_both_szns.csv", col_names=FALSE) %>%
print(n=Inf)
```

## Airdrop Memes SZN2
```{r}
c(airdrop_memes_szn2) %>%
tally() %T>%
readr::write_csv(file="airdrop_memes_10_szn2.csv", col_names=FALSE) %>%
print(n=Inf)
```

## Airdrop Gradients
```{r}
c(airdrop_gradient) %>%
tally() %T>%
readr::write_csv(file="airdrop_gradient_5.csv", col_names=FALSE) %>%
print(n=Inf)
```

## Airdrop Artist
```{r}
c(airdrop_eric) %>%
tally() %T>%
readr::write_csv(file="airdrop_artist.csv", col_names=FALSE) %>%
print(n=Inf)
```

## Airdrop Artist 2
```{r}
c(airdrop_eric2) %>%
tally() %T>%
readr::write_csv(file="airdrop_artist2.csv", col_names=FALSE) %>%
print(n=Inf)
```




## Allow Artist Editions Phase 1
```{r}
c(allow_eric_editions) %>%
tally() %T>%
readr::write_csv(file="allow_artist_editions_phase1.csv", col_names=FALSE) %>%
print(n=Inf)
```

## Allow Gradient Phase 1
```{r}
c(allow_gradient_phase1) %>%
tally() %T>%
readr::write_csv(file="allow_gradient_phase1.csv", col_names=FALSE) %>%
print(n=Inf)
```

## Allow Memes 1 Phase 1 (Full Set Both SZNs)
```{r}
c(allow_memes_1_phase1) %>%
tally() %T>%
readr::write_csv(file="allow_memes_full_both_szns_phase1.csv", col_names=FALSE) %>%
print(n=Inf)
```

## Allow Memes 2 Phase 1 (Full Set SZN2)
```{r}
c(allow_memes_2_phase1) %>%
tally() %T>%
readr::write_csv(file="allow_memes_full_szn2_phase1.csv", col_names=FALSE) %>%
print(n=Inf)
```

## Allow Memes 3 Phase 1 (Next Top 200)
```{r}
c(allow_memes_3_phase1) %>%
tally() %T>%
readr::write_csv(file="allow_memes_200_phase1.csv", col_names=FALSE) %>%
print(n=Inf)
```

## Allow Memes 4 Phase 1 (Random 69 from remaining)
```{r}
c(allow_memes_4_phase1) %>%
tally() %T>%
readr::write_csv(file="allow_memes_random69_phase1.csv", col_names=FALSE) %>%
print(n=Inf)
```





## Allow 6529
```{r}
c(allow_raw, allow_singles) %>%
tally() %T>%
readr::write_csv(file="allow_6529_phase2.csv", col_names=FALSE) %>%
print(n=Inf)
```

## Allow Memes Phase 2 (Remaining from Top 500)
```{r}
c(allow_memes_phase2) %>%
tally() %T>%
readr::write_csv(file="allow_memes_phase2.csv", col_names=FALSE) %>%
print(n=Inf)
```





## All Memes
```{r}
c(airdrop_memes_all, airdrop_memes_szn2,allow_memes_1_phase1,allow_memes_2_phase1,allow_memes_3_phase1,allow_memes_4_phase1,allow_memes_phase2) %>%
tally() %T>%
readr::write_csv(file="all_memes.csv", col_names=FALSE) %>%
print(n=Inf)
```


## Versioning
```{r}
R.version$version.string
packageVersion("tidyverse")
packageVersion("magrittr")
```
